### ISSUE TITLE
Generated whitepaper living document or not?

### ISSUE THREAD

**Issue by daya** [bigchaindb/whitepaper#15]
Executed `build.sh` got `bigchaindb-whitepaper.pdf` but it still has the same warning 
```
THIS IS NO LONGER A LIVING DOCUMENT. SIGNIFI- CANT CHANGES MADE SINCE JUNE 8, 2016 ARE NOTED IN AN ADDENDUM ATTACHED AT THE END. ALSO SEE THE LATEST BIGCHAINDB SERVER DOCUMENTATION AND THE BIGCHAINDB BLOG. WE ARE PLANNING TO RELEASE AN UPDATED VERSION OF THIS DOCUMENT CIRCA THE RE- LEASE OF BIGCHAINDB VERSION 2.
```
So is this a living document or not, if not then could you pls point me to the most recent white paper ?

**Comment by kremalicious** [comment]
In short: we wrote a new one and are in the process of adding it back to our website: https://github.com/bigchaindb/site/pull/233
