### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by alpyne** [bigchaindb/whitepaper#3]
**Section 4.5.2. Block Model:**

_In code block:_

> "voters": ["<list of federation nodes **pulic** keys>"]

/pulic/public

> id: SHA3 hash of the current block. This is also a DB primary key, to ensure **we** that all blocks are unique.

Drop "we"

> votes: Initially an empty list. Nodes in the voters list will append to it **has** they vote on the block

^has^as

**Section 4.6. Block Validity and Blockchain Pipelining**

_In footnotes:_

> 9 For example: the order of events in RethinkDB is **guarantueed** by the Raft consensus and does not depend on timing.

/guarantueed/guaranteed

> If for some reason, the nodes disagree on the parent (**eg.** malicious nodes) **on** can just mark the block as invalid, 

/eg./e.g.
/on/one

> which is basically **and** open broadcast channel (instead of **on** communicating individually with each node)

/and/an
Drop "on"

**Comment by ttmc** [comment]
Thanks @alpyne ! I've been editing the whitepaper (draft) and just finished repairing these errors. I didn't push them to this repository yet; I still have some other edits I need to do first. I'll leave this issue open until then.

**Comment by ttmc** [comment]
Resolved by commit https://github.com/bigchaindb/whitepaper/commit/c0bbb07ee39b314c2c9d3bbafed607cf2b15f1f1
